Repository cncf/tag-contributor-strategy, pull requests merged in 2023-07, with the labels that each got.

#457 Add project board / roadmap info to the getting started guide
  website/content/contributors/getting-started.md
Labels: wg/contribgrowth

#446 Create meeting-moderation.md
  website/content/maintainers/community/contributor-growth-framework/meeting-moderation.md
Labels: wg/contribgrowth, needs-liaison-approval

#465 Add the cncf/students repo to getting-started.md
  website/content/contributors/getting-started.md
Labels: administration

#395 TAG CS Glossary
  website/content/about/_index.html
  website/content/contributors/_index.md
  website/content/maintainers/_index.md
  website/content/resources/glossary.md
Labels: website

#469 Cleanup README.md - Remove dead links
  README.md
Labels: administration
