Repository cncf/tag-contributor-strategy, pull requests merged in 2023-09, with the labels that each got.

#511 update setting.yml file removing user access list
  .github/settings.yml
Labels: administration

#532 update new Co-Chair to README.md
  deaf-and-hard-of-hearing/README.md
Labels: wg/contribgrowth

#533 Co-chair update
  deaf-and-hard-of-hearing/README.md
Labels: deaf/hoh
